node_js:
  - "0.10"

# whitelist
branches:
  only:
    - travis
    - develop

install:
  - npm install
  - bower install
  - bundle install

before_script:
  - cp _config.sample.yml _config.yml

script:
  - bundle exec rake generate
  - rake linklint

#add after_script to deploy to s3
